# Generated by Django 5.0.3 on 2024-03-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
